###############################################################################
# Copyright (c) 2016-22, Lawrence Livermore National Security, LLC and CHAI
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
###############################################################################

###############################################################################
# General GitLab pipelines configurations for supercomputers and Linux clusters
# at Lawrence Livermore National Laboratory (LLNL).
#
# This entire pipeline is LLNL-specific
# #############################################################################

# We organize the CI on Gitlab in sub-pipelines. Each sub-pipeline correspond
# to a test phase on a given machine. This design is simpler and more scalable
# than doing the same with stages.

# The stages in the top-level pipeline described here correspond to high level
# steps in the testing workflow.
# TODO: rehabilitate multi-project and branch radiuss-spack-testing.
stages:
  - build-and-test
  - multi-project # unused so far
  - radiuss-spack-testing # unused so far

# Note: Compared to Umpire CI, CHAI is not using service users or a custom build
# directory.

# Trigger sub-pipelines:
ruby-build-and-test:
  stage: build-and-test
  variables:
    # Explicitly pass down variables that we want to be able to set when
    # triggering pipelines manually or using scheduling.
    ALL_TARGETS: "${ALL_TARGETS}"
    ON_RUBY: "${ON_RUBY}"
  trigger:
    include: .gitlab/ruby-build-and-test.yml
    strategy: depend

#corona-build-and-test:
#  stage: build-and-test
#  variables:
#    ALL_TARGETS: "${ALL_TARGETS}"
#    ON_CORONA: "${ON_CORONA}"
#  trigger:
#    include: .gitlab/corona-build-and-test.yml
#    strategy: depend

lassen-build-and-test:
  stage: build-and-test
  variables:
    ALL_TARGETS: "${ALL_TARGETS}"
    ON_LASSEN: "${ON_LASSEN}"
  trigger:
    include: .gitlab/lassen-build-and-test.yml
    strategy: depend
